version: 2
updates:
  # Backend dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    allow:
      - dependency-type: "production"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "team-backend"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]

  # Frontend dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    allow:
      - dependency-type: "production"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "team-frontend"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]