apiVersion: v1
kind: Secret
metadata:
  name: saas-metrics-secrets
  namespace: default
  labels:
    app: saas-metrics
    component: secrets
    managed-by: kubernetes
  annotations:
    rotation.kubernetes.io/schedule: "90d"
    encryption.kubernetes.io/cipher: "AES-256-GCM"
    backup.kubernetes.io/schedule: "daily"
    backup.kubernetes.io/retention: "30d"
type: Opaque
data:
  # Database Credentials
  DB_HOST: ZGItaG9zdC5wcm9kLnNhYXNtZXRyaWNzLmNvbQ== # db-host.prod.saasmetrics.com
  DB_PORT: NTQzMg== # 5432
  DB_NAME: c2Fhc19tZXRyaWNzX3Byb2Q= # saas_metrics_prod
  DB_USER: c2Fhc19tZXRyaWNzX2FwcA== # saas_metrics_app
  DB_PASSWORD: U3VwZXJTZWNyZXRQYXNzd29yZDEyMyE= # SuperSecretPassword123!
  DB_SSL_MODE: dmVyaWZ5LWZ1bGw= # verify-full
  DB_SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  DB_SSL_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...
  DB_SSL_ROOT_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...

  # Authentication Configuration
  GOOGLE_OAUTH_CLIENT_ID: MTIzNDU2Nzg5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_OAUTH_CLIENT_SECRET: R09PQ19TRUNSRVQ=
  JWT_SECRET_KEY: c3VwZXJfc2VjcmV0X2p3dF9rZXlfMjAyNA==
  JWT_REFRESH_KEY: cmVmcmVzaF9rZXlfMjAyNA==
  JWT_ALGORITHM: SFMyNTY= # HS256
  JWT_EXPIRY: MTgwMA== # 1800 (30 minutes)
  JWT_REFRESH_EXPIRY: NjA0ODAw # 604800 (7 days)

  # Encryption Keys
  DATA_ENCRYPTION_KEY: QUVTXzI1Nl9HQ01fS0VZXzIwMjQ=
  DATA_ENCRYPTION_IV: UkFORE9NX0lWXzIwMjQ=
  BACKUP_ENCRYPTION_KEY: QkFDS1VQX0tFWV8yMDI0
  BACKUP_ENCRYPTION_IV: QkFDS1VQX0lWXzIwMjQ=
  KEY_ROTATION_SECRET: Uk9UQVRJT05fU0VDUkVUXzIwMjQ=

  # Cache Configuration
  REDIS_HOST: cmVkaXMtbWFzdGVyLnByb2Quc2Fhc21ldHJpY3MuY29t
  REDIS_PORT: NjM3OQ== # 6379
  REDIS_PASSWORD: UmVkaXNTdXBlclNlY3JldFBhc3N3b3JkMTIzIQ==
  REDIS_TLS_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...
  REDIS_TLS_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  REDIS_TLS_CA_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...